# config
cover: /img/bg_img.jpg
logo: /img/logo.png
top_saying:
- title: Welcome to <span>GP Podcast</span> Website, WELCOME.
- content: Something content
bottom_saying: Papa Bless!
# Content
excerpt_link: Read More

rss: /atom.xml

highlightjs: vs

#Works
works:
- works_name: AAA
  works_url: /
- works_name: BBB
  works_url: /atom.xml

#duoshuo name
duoshuo:

#disqus name
disqus_shortname: pkpersonal

#fancybox
fancybox: true

# Miscellaneous
github: https://github.com/G1edriusLt
twitter: https://twitter.com/G1edriusLt
facebook: 
google: 
weibo: 

#about  timeline
timeline:
- num: 1
  word: 2014/06/12-Start
- num: 2
  word: 2014/11/29-XXX
- num: 3
  word: 2015/02/18-DDD
- num: 4
  word: More

#Links
links:


# Local search
# Dependencies: https://github.com/flashlab/hexo-generator-search
local_search:
  enable: true
  # if auto, trigger search by changing input
  # if manual, trigger search by pressing enter key or search button
  trigger: auto
  # show top n results per article, show all results by setting to -1
  top_n_per_article: 2
