# ===========================================
# Site Settings
# ===========================================
# Header
site_title: Toasted Buns
site_description: One toasted bun at a time
# ---Optional ---
site_avatar: /images/avatar.jpeg
artical_license_statement:
# ---End Optional ---
menu:
  Home: /
  Archives: /archives
  About: /about

# display widgets
widgets:
#- search
- recent_posts
- archives
- social_links
# widget behavior
archive_type: 'monthly'
show_count: true
# Content
excerpt_link: Read More
# favico 
favicon: images/favicon.ico

# ===========================================
# Miscellaneous Settings
# ===========================================
# Baidu Analytics
baidu_analytics: 
# Google Analytics
google_analytics: UA-121640466-1
comment: true
comments:
  # Disqus comments
  disqus_shortname: 
  # Facebook comments
  facebook:
    appid: 2127422100867738
    comment_count: 5
    comment_colorscheme: light
# Disqus
disqus:
  enable: false
  shortname: pkpersonal
  count: true
# changyan
changyan:
  enable: false
  appid:
  appkey:
# duoshuo
duoshuo:
  enable: false
  shortname: troyyang
# Visitors
leancloud_visitors:
  enable: false
  app_id: 
  app_key: 

# Search 
# Note: please install hexo-generator-search plugin and config the root _config.yml (not theme's _config.yml) as below value search.json(https://www.npmjs.com/package/hexo-generator-search):
#search:
#  path: search.json
#  field: post
