# Header Menu. title: link
menu:
  Whoami: /whoami
  Github: https://github.com/G1edriusLT
  Twitter: https://twitter.com/G1edriustLT


# 查看文章时是否自动播放音乐
autoplay: false
# 博客文章默认音乐, 优先级: 1.文章头mp3参数> 2.在这里配置
mp3: http://link.hhtjim.com/163/425570952.mp3
# 首页封面图, 优先级: 1.在这里配置> 2.文章头cover参数;
welcome_cover: # /img/welcome-cover.jpg
# 文章封面图, 优先级: 1.文章头cover参数 > 2.在这里配置
cover: /img/cover.jpg


keywords: Fechin 
# 要使用google_analytics进行统计的话，这里需要配置ID
google_analytics: UA-121084299-1
# 网站ico
favicon: /img/favicon.png
rss: atom.xml
